import 'bootstrap/dist/css/bootstrap.min.css';
import { AppProps } from 'next/app';
import Head from 'next/head';
import { NotificationProvider } from '../components/organisms/Notification';
import styles from '../styles/Home.module.css';
import { useCurrentUser, UserAuthProvider } from '../src/utils/userAuth';
import React from 'react';
import { useRouter } from 'next/router';
import { WebSocketProvider } from '../src/utils/webSocket';
import TopNavbar from '../components/organisms/TopNavBar';
import SuggestOpenByMobile from '../components/organisms/SuggestOpenByMobile';

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  let isMobile: boolean = false;
  if (typeof window == 'object') {
    isMobile = !!window.navigator.userAgent.match(/iPhone/);
  }

  return (
    <div className={styles.body}>
      <Head>
        <title>Winning Fish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/earlyaccess/nicomoji.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossOrigin="anonymous"
        />
      </Head>
      <NotificationProvider>
        <UserAuthProvider>
          <WebSocketProvider>
            {isMobile ? (
              <>
                <MyappInit />
                <TopNavbar />
                <Component {...pageProps} />
              </>
            ) : (
              <SuggestOpenByMobile />
            )}
          </WebSocketProvider>
        </UserAuthProvider>
      </NotificationProvider>
    </div>
  );
};

const MyappInit: React.FC = () => {
  const currentUser = useCurrentUser();
  const router = useRouter();
  const isAdmin = router.asPath.startsWith('/_admin');

  React.useEffect(() => {
    if (isAdmin && currentUser && currentUser.role !== 1) {
      router.push('/');
    }
  }, [router, currentUser, isAdmin]);

  return null;
};

export default MyApp;
