import '../styles/globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { AppProps } from 'next/app';
import Head from 'next/head';
import { NotificationProvider } from '../components/Notification';
import styles from '../styles/Home.module.css';
import { useFetchCurrentUser, UserAuthProvider } from '../src/utils/userAuth';
import React from 'react';

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  // const fetchCurrentUser = useFetchCurrentUser();

  // React.useEffect(() => {
  //   fetchCurrentUser();
  // }, [fetchCurrentUser]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossOrigin="anonymous"
        />
      </Head>
      <NotificationProvider>
        <UserAuthProvider>
          <Component {...pageProps} />
        </UserAuthProvider>
      </NotificationProvider>
    </div>
  );
};

export default MyApp;
